from .validation import EnvironInputModel as EnvironInputModel, ExternalModel as ExternalModel, ExternalsContainer as ExternalsContainer, RegionModel as RegionModel, RegionsContainer as RegionsContainer
from typing import Any, Dict

class Input:
    file: Any = ...
    params: Any = ...
    def __init__(self, natoms: int, filename: str=...) -> None: ...
    def _get_input_param_dict(self) -> Dict[str, Any]: ...
    def _process_externals(self, data: Dict[str, str]) -> ExternalsContainer: ...
    def _process_regions(self, data: Dict[str, str]) -> RegionsContainer: ...

def by_group(x: Any): ...
def main() -> None: ...
